name: Verify package
on:
  pull_request:
    branches:
    - master
jobs:
  VerifyPackage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create packages
      run: dotnet pack Template.csproj -o Packages -c Release -p:PackageVersion=0.0.0
    - name: Install template
      run: dotnet new --install ./Packages/Staticsoft.Template.Library.0.0.0.nupkg
    - name: Create new solution
      run: dotnet new staticsoft-lib -n Solution
    - name: Build solution
      run: dotnet build Solution/Library.sln